# Generated by Django 6.0.4 on 2026-04-15 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('branch', models.CharField(choices=[('CS', 'CS'), ('IT', 'IT'), ('Mechanical', 'Mechanical')], max_length=20)),
                ('semester', models.PositiveSmallIntegerField()),
                ('division', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['branch', 'semester'], name='analytics_s_branch_eeb6b7_idx'), models.Index(fields=['division'], name='analytics_s_divisio_1696aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField()),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='analytics.student')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'semester'], name='analytics_g_student_8dc675_idx'), models.Index(fields=['semester', 'cgpa'], name='analytics_g_semeste_03c2e4_idx')],
                'unique_together': {('student', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('total_classes', models.PositiveSmallIntegerField()),
                ('attended_classes', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='analytics.student')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'date'], name='analytics_a_student_e6221f_idx'), models.Index(fields=['subject', 'date'], name='analytics_a_subject_003a55_idx')],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('academic', 'academic'), ('extracurricular', 'extracurricular')], max_length=20)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='analytics.student')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'date'], name='analytics_a_student_6668a3_idx'), models.Index(fields=['type', 'date'], name='analytics_a_type_e4e8a8_idx')],
            },
        ),
    ]
